### ISSUE TITLE
Invalid username or password, try again

### ISSUE THREAD

**Issue by GaneshKandu** [pHAlkaline/phkondo#16]
Hi,
I Have Installed  phKondo 1.5
In My Machine
I am only Administrator in it
and just edited my password and unchecked Active checkbox
Now I am unable to Login. Getting Invalid username or password

**Please let me Know How to Login ??**

**Comment by pHAlkaline** [comment]
Hello, Thanks for your interest in pHKondo.
User must be active to be able to login.
Why did you unchecked Active?

**Comment by GaneshKandu** [comment]
I didn't know why this Active checkbox is Given ??

**Comment by GaneshKandu** [comment]
**Resolved**, Change value of active to 1 in users table
