### ISSUE TITLE
An Internal Error Has Occurred. PHP 5.3

### ISSUE THREAD

**Issue by GaneshKandu** [pHAlkaline/phkondo#17]
Hi
Getting An Internal Error Has Occurred. on PHP 5.3

[https://github.com/pHAlkaline/phkondo/wiki/Install#requirements](https://github.com/pHAlkaline/phkondo/wiki/Install#requirements)
## Requirements

- HTTP Server with mod_rewrite or similar.
- PHP 5.3 or higher.
- PHP Ext mcrypt.
- MySQL 5.1 or higher.
- All built-in drivers require PDO. You should make sure you have the correct PDO extensions installed.

I tried to Debug and Found Following Error 

you have used Short array tag at Many places no longer Support in PHP 5.3

## syntax error, unexpected '['

> app/Model/User.php Lone142

```php
public $belongsTo = array
	('Entity'=> [
		'foreignKey' => 'foreign_key',
		'conditions' => ['User.model' => 'Entity']
	//'joinType' => 'LEFT'
]);
```
	
> app/Model/Entity.php Line 78

```php
public $hasOne = array('User'=>[
		'foreignKey' => 'foreign_key',
		'conditions' => ['User.model' => 'Entity'],
		'dependent' => true,
	]);
```
> app/Controller/IncomeController.php Line 79

```php
$conditions['conditions']['And'] = ['payment_date BETWEEN ? AND ?' => array($open_date, $close_date)];
```

**Comment by pHAlkaline** [comment]
Only supported in 5.4 .. requirements must be updated
