### ISSUE TITLE
Since PHP 7.2 the mcrypt extension isn't released anymore since it was deprecated for 7.1

### ISSUE THREAD

**Issue by robertjota** [pHAlkaline/phkondo#20]
The composer.json file does allow it to be installed with PHP 7.2. An upgrade should be made to the library to move away from mcrypt.

**Comment by pHAlkaline** [comment]
What is your version of pHKondo?

check composer json file for ...

 "require": {
.....
         "ext-openssl": "*",
......
          },

and app\Config\core_phapp.php for

Configure::write('Security.useOpenSsl', true);

**Comment by pHAlkaline** [comment]
closing ...
