### ISSUE TITLE
403 Forbidden error 

### ISSUE THREAD

**Issue by webmarkcompt** [pHAlkaline/phkondo#21]
Hi guys

I am strugling with a annoying "403 Forbidden error" when I am trying to update a receipt and save the changes.

I already change the permissions of tmp to 777 but without success.

Any idea what it could be?

https://www.accmatosinhos.pt/condo/receipts/pay_receipt/6?condo_id=1
```

Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by pHAlkaline** [comment]
hi ,
turn on debugging and send us more detailed information

https://github.com/pHAlkaline/phkondo/wiki/Troubleshooting

**Comment by webmarkcompt** [comment]
Hi

I turned on the debugging but there isn´t any error on log

Can you check by the user access and reproduce the issue?

https://www.accmatosinhos.pt/condo

--- Information Removed ----

<img width="668" alt="Captura de ecrã 2021-01-21, às 23 21 08" src="https://user-images.githubusercontent.com/8679845/105424476-5beebe00-5c3f-11eb-9bcb-9361fab9dfbb.png">

<img width="1439" alt="Captura de ecrã 2021-01-21, às 23 20 23" src="https://user-images.githubusercontent.com/8679845/105424414-41b4e000-5c3f-11eb-9528-b426a4dcd75d.png">

**Comment by pHAlkaline** [comment]
You are trying to "pay" receipt with id 6 on condo with id 1 .. probably you dont have receipt with id 6 on condo with id 1 
 
https://www.accmatosinhos.pt/condo/receipts/pay_receipt/6?condo_id=1 

not save to put your passwords here .. :-)  ...  you better delete previous post

**Comment by webmarkcompt** [comment]
Hi!

I have a receipt in condo 1 but id 7...

Could this happen because I deleted a receipt before?
I can do that right?

Now was easy to found the ID correct but with the condoms in production...

Anyway
Thanks for your precious help!!
Be safe!

<img width="1996" alt="Captura de ecrã 2021-01-22, às 12 18 05" src="https://user-images.githubusercontent.com/8679845/105489909-e7059d80-5cab-11eb-9bbe-c3f1bcddaabd.png">
<img width="1201" alt="Captura de ecrã 2021-01-22, às 12 15 30" src="https://user-images.githubusercontent.com/8679845/105489916-ea008e00-5cab-11eb-9065-431f3abba846.png">

**Comment by pHAlkaline** [comment]
Thanks for your preference .. keep save
