### ISSUE TITLE
error in app/view/themed/phkondo/pages/login.ctp

### ISSUE THREAD

**Issue by ivus84** [pHAlkaline/phkondo#7]
found error in login page 

it should be 
        <?php if (Configure::read('Application.mode') == 'demo') { ?>
instead of 
        <?php if (Configure::write('Application.mode') == 'demo') { ?>

otherwise it will always show "demo" stuff even if application mode is not "demo"

same in app/view/themed/phkondo/users/login.ctp

**Comment by pHAlkaline** [comment]
Done!
